### ISSUE TITLE
flow-cli/process-tester:requries additional documentation

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#11]
**Relevant Flow module(s)**
flow-cli
process-tester

**What do you want to accomplish? Please describe.**
Would be nice with some more detailed documentation. (current: https://flow-docs.stacc.dev/framework/flow-process/10.6/testing)
 

**Describe the suggested solution**
E.g: yaml described a series of _types_
These should be listed in detail:
 - what do they do
 - what args

Configuration: All process tests need to be listed in a single dir (not allowed to nest files)
 - would be nice with if we could permit a nested structure as this dir can easily become cluttered

**Comment by Anders-eide-stacc** [comment]
The process-tester tool could probably use some more love in general.

I am thinking I will write up some documentation when I move it over to the Stacc CLI and then hopefully have time to implement some extra features for it as well.
