### ISSUE TITLE
Flow-process: timestamp in json log structure

### ISSUE THREAD

**Issue by torhagl** [stacc/stacc-flow-community#28]
**Relevant Flow module(s)**
Flow-process

**What do you want to accomplish? Please describe.**
Timestamp in the json log structure, so that parses are able to see the timestamp.

**Describe the suggested solution**
A timestamp in the json structure with the key 'timestamp'

**Additional context**
For instance humanlog parser is not able to get the timestamp of each log line without this label, see screenshot where timestamp is 1 jan 1970 on every log line:

![image](https://user-images.githubusercontent.com/26787631/139404976-76d6af53-7f86-4b22-ad0f-0fedbceb8d59.png)

**Comment by Anders-eide-stacc** [comment]
Added in `v11.1`
