### ISSUE TITLE
Stacc CLI: only push handlers for specific process by specifying flag on stacc push command

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#29]
Only push handlers for specific process by specifying process name via flag; e.g., _--process onboarding_

**Comment by sondregj** [comment]
Why is this a desired feature?

**Comment by hpl002** [comment]
So that I do not have to wait for irrelevant processes to be diffed, validated, and then potentially deployed?

Reduce waiting time

**Comment by hpl002** [comment]
@sondregj  status?
progress or close issue

**Comment by sondregj** [comment]
Probably close. IMO this should rather be optimized within Process.

**Comment by hpl002** [comment]
If this is still an issue after migrating to the _new_ setup then i will perform a benchmark and collect metrics.
