### ISSUE TITLE
Case Manager: Show referenceId on flows in queue item

### ISSUE THREAD

**Issue by Anders-eide-stacc** [stacc/stacc-flow-community#3]
**Is your feature request related to a problem? Please describe.**
Flow Process lets me customize the referenceId and referenceName of flows, but this is not shown in my queues.

**Describe the solution you'd like**
I would like the queue to display my customized referenceName if set and referenceId as fallback

**Additional context**

![image](https://user-images.githubusercontent.com/70014598/116689896-eff7c080-a9b8-11eb-8195-c0e9fe5a5535.png)

**Comment by Karolined** [comment]
Fixed in @flow/case-manger v.13
Will display both referenceName and referenceId in default queue item when they are set, with fallback to flowDefinitionId and legacy flow number.
