### ISSUE TITLE
case-manager: does not show pending message task in list of tasks after first completion

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#30]
Created diagram with event sub-process. This holds a single message-start event.

This task renders nicely in the task list before first completion. 

Expected behavior would be that the task i appended to list after completion as it is available.

**Comment by Anders-eide-stacc** [comment]
Could you include a screenshot of the relevant bpmn here?

Is this an interrupting message start event, or a non-interrupting one?

**Comment by Anders-eide-stacc** [comment]
This was an issue with event-based sub-processes using non-interrupting message start events.

Fixed in `v10.10.1003`.
Not an issue in v11
