### ISSUE TITLE
CLI: forcefully delete file

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#33]
**Relevant Flow module(s)**
stacc-cli
stacc-cli-next

**What do you want to accomplish? Please describe.**
CLI should have some mechanism for deleting a specific file.

We currently have to either be in _watch mode_ for it to register the local deletion, or delete the entire bucket.

**Describe the suggested solution**
stacc delete -f <regex>
stacc delete --file <regex>

**Comment by sondregj** [comment]
If I understand the problem correctly, this does not apply to `stacc-cli-next`.

**Comment by hpl002** [comment]
> If I understand the problem correctly, this does not apply to `stacc-cli-next`.

Not sure, i assumed that you use the same pattern.

Has this been addressed in stacc-cli-next? If so, then how? Can this be ported to stacc-cli?

**Comment by sondregj** [comment]
The problem has been solved at a more fundamental level, by leveraging immutable artifacts for the entire "bucket". All files are replaced every time a change is made.

Given that the new version is intended to replace the existing one, and that porting a complete solution would require a number of changes, it would probably not be worth it. A command for deleting a single file as described may be an option, but the best thing would be to use the new system.
