### ISSUE TITLE
Flow process fails to load transitive dependency

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#35]
**Module and version**
FP version=10.10.1039

**Describe the bug**
Flow process failed with error SIGABR. When the container restarted it tried to load node_modules, but failed to load all required transitive deps. This led to an axios error. Fixed the error by killing pod which then again reloads all modules from scratch(i assume?)

**To reproduce**
Fairly certain that you will be able to reproduce this if you try to add and remove node_modules and then push using the stacc push command. After a few cycles you will create a scenario where its out of sync.

**Expected behavior**
Expected a 1-1 relationship from my local modules to the modules installed on remote.

 
**Additional context**
Not sure, but assuming that this is resolved with the new build and deploy mechanism. If so then feel free to delete issue. :)

**Comment by hpl002** [comment]
`{"message":["Failed to complete task 'create-agreement-document'. No more retries","TypeError: Cannot read property 'transitional' of undefined\n    at transformResponse (/app/config/node_modules/axios/lib/defaults.js:82:29)\n    at transform (/app/config/node_modules/axios/lib/core/transformData.js:16:12)\n    at Object.forEach (/app/config/node_modules/axios/lib/utils.js:218:10)\n    at transformData (/app/config/node_modules/axios/lib/core/transformData.js:15:9)\n    at onAdapterResolution (/app/config/node_modules/axios/lib/core/dispatchRequest.js:63:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async Object.execute (/app/config/onboarding/handlers/service-tasks/create-agreement-document.js:214:49)\n    at async Object.executeServiceTask (/app/src/handler/index.js:223:20)\n    at async executeServiceTask (/app/src/process-engine/service-tasks.js:124:10)\n    at async handleServiceTask (/app/src/process-engine/service-tasks.js:52:20)\n    at async work (/app/src/process-engine/event-listener.js:118:18)\n    at async processMsg (/app/src/process-engine/event-listener.js:65:20)",{"id":"a310c040-6198-11ec-a8e8-e6ca6b2e7577"}],"level":"error"}`

**Comment by oyvindfanebust** [comment]
Hi!

This issue is fixed in 11.2.1079.

**Comment by hpl002** [comment]
Ported to 10.10.1080
