### ISSUE TITLE
FP: Improved logging or validation of map funtion in handlers

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#45]
**Relevant Flow module(s)**
FP

**What do you want to accomplish? Please describe.**
Developer had issues with locating why FP was bugging. Turns out the map function was lacking a return statement. This can be  somewhat difficult to capture.

The error returned from FP is also not very informative. This can be made simpler/more informative.

**Describe the suggested solution**
1. Better runtime logging  

2. Static validation.   
A missing return statement in the map function will always result in a bug. However, not all handlers need a map at all.
If map exists, then it must contain a return statement. If you do not need to map anything to state then omit the function entirely. 

**Additional context**
[Internal reference](https://stacc-as.slack.com/archives/C02B19DAFJQ/p1643198495128800)

**Comment by Anders-eide-stacc** [comment]
Added more informative runtime error message in v11.2 for now.

If we have spare capacity, static validation might be added at some point in the future, but for now, this is not a priority.

![image](https://user-images.githubusercontent.com/70014598/151347570-5842195e-0236-4a70-ae54-0993299283f3.png)
