### ISSUE TITLE
FP: expand user-task permissions with flag that completely hides task or change definition of read permission

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#48]
**Relevant Flow module(s)**
FP

**What do you want to accomplish? Please describe.**
Current interface:
``` JS
  getTaskPermissions: ({ user, task, context }) => ({
    read: true,
    save: true,
    complete: true,
    assign: true,
    unassign: true
  })
```

While i can completely hide the context i cannot hide the task itself. Some tasks should never be made available at all(unless current user meets criteria).
 - Hiding the context while not hiding the task in the caseworker portal can actually be a bit confusing.

**Describe the suggested solution**
Expand with a new flag or change the definition of the read permission.

**Additional context**

**Comment by Anders-eide-stacc** [comment]
Hmm, not sure I understand the case here.

If you don't have `read`-permission on the task, then it will not be displayed at all (it will not be returned from the API either).
Could you elaborate further here?

**Comment by hpl002** [comment]
Solved ✅ 

Implementation bug on my side. Had some error handling that was way too friendly and did not respect the http 403 response.
