### ISSUE TITLE
Caseworker portal: Missing translations for taskId when rendering via search app

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#53]
**Module and version**
```
"@flow/buttons": "^12.1",
"@flow/case-manager": "^12.2",
"@flow/components": "^12.1",
"@flow/icons": "^12.1",
"@flow/modal": "^12.1",
"@flow/style": "^12.0",

```
**Describe the bug**
Missing translations for taskId when rendering via search app

**To reproduce**
1. Open case via the search app.
2. See taskId via history tab
3. Locate the same case via the regular task queue
4. compare

**Expected behavior**
Expected to see the same translations as if i were to open it via the case queue.

**Comment by Karolined** [comment]
This is not a bug, but a feature 😄  Translations can be specified either for all apps, or for a specific app. 
For example when translations are configured with `app: APPS.INBOX`, these translations are only used in the inbox app. If you do not specify a `app` key, the translations are used for all apps. Documentation [here]( https://developer.stacc.dev/flow/case-manager/Docs/configuration#language-and-translations)
