### ISSUE TITLE
Case Manager: Sorting custom task lists by translated task title

### ISSUE THREAD

**Issue by Karolined** [stacc/stacc-flow-community#59]
**Relevant Flow module(s)**
@flow/case-manger
https://developer.stacc.dev/flow/case-manager/Docs/Case/#replacing-task-lists

**What do you want to accomplish? Please describe.**
When implementing custom tasks lists for the case overview, I want to sort the tasks in the list by the translated version of the title.

(Sorting is available today, but translations happens afterwards and map has no access to the translations function)

**Comment by karoline-stacc** [comment]
Solved in @flow/case-manager v.14.2.0
https://developer.stacc.dev/flow/case-manager/latest/changelog#v1420
